homeassistant:
  # Name of the location where Home Assistant is running
  name: Home
  # Location required to calculate the time the sun rises and sets
  latitude: -41.2848
  longitude: 174.75636
  # Impacts weather/sunrise data (altitude above sea level in meters)
  elevation: 285
  # metric for Metric, imperial for Imperial
  unit_system: metric
  # Pick yours from here: http://en.wikipedia.org/wiki/List_of_tz_database_time_zones
  time_zone: Pacific/Auckland
  # Customization file
  customize: !include customize.yaml
  packages: !include_dir_named packages

# Enables the frontend
frontend:

# Enables configuration UI
config:

http:
  # Secrets are defined in the file secrets.yaml
  # api_password: !secret http_password
  # Uncomment this if you are using SSL/TLS, running in Docker container, etc.
  # base_url: example.duckdns.org:8123

# Checks for available updates
# Note: This component will send some information about your system to
# the developers to assist with development of Home Assistant.
# For more information, please see:
# https://home-assistant.io/blog/2016/10/25/explaining-the-updater/
updater:
  # Optional, allows Home Assistant developers to focus on popular components.
  # include_used_components: true

# Discover some devices automatically
discovery:

# Allows you to issue voice commands from the frontend in enabled browsers
conversation:

# Enables support for tracking state changes over time
history:

# View all events in a logbook
logbook:

# Enables a map showing the location of tracked devices
map:

# Track the sun
sun:

# Weather prediction
sensor:
  # - platform: speedtest
  #   monitored_conditions:
  #     - ping
      # - download
      # - upload
      
# Clock
  - platform: time_date
    display_options: 
      - 'time'
  
      
  - platform: template
    sensors:
      # solar_angle:
      #   friendly_name: "Sun Angle"
      #   unit_of_measurement: '°'
      #   value_template: "{{ '%f'|format(states.sun.sun.attributes.elevation) }}"

      recycling:
        value_template: >
          {% if now().isocalendar()[1]%2==0 %}
            bottles
          {% else %}
            plastics
          {% endif %}
          
  - platform: dishes
  
  - platform: chores
  
  - platform: rubbish
  
  - platform: mqtt
    name: Kitchen Temperature
    state_topic: kitchen/temperature
    unit_of_measurement: "°C"
    
  - platform: mqtt
    name: Ben's Bedroom
    state_topic: ben/temperature
    unit_of_measurement: "°C"

    
      
camera:
# Lower Hutt Motorway
  - platform: generic
    name: Lower Hutt Traffic
    still_image_url: http://www.trafficnz.info/camera/278.jpg

  - platform: generic
    name: Wellington Traffic
    still_image_url: http://www.trafficnz.info/camera/230.jpg

# Text to speech
tts:
  - platform: google

# Cloud
cloud:

# devices
device_tracker:
  - platform: ping
    hosts:
      Benjamin: 192.168.1.30
      Dylan: 192.168.1.31
      David: 192.168.1.32
      Jacob: 192.168.1.33
      
shopping_list:

panel_iframe:
  nodered:
    title: 'Automations'
    url: 'http://192.168.1.9:1880'
  ide:
    title: 'Editor'
    url: 'http://192.168.1.9:8321/ide.html'
    
mqtt:

weather:
  platform: darksky
  name: Weather Today
  units: si
  api_key: !secret darksky_api_key
  
# Allow diagnosing system problems
system_health:
  
group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
