homeassistant:
  name: Benghazi Studios
  latitude: -36.8956173
  longitude: 174.8660777
  elevation: 10
  unit_system: metric
  time_zone: "Pacific/Auckland"
  external_url: !secret external_url
  internal_url: !secret internal_url
  media_dirs:
    media: "/media"
  auth_providers:
    - type: homeassistant

default_config:

# Text to speech
tts:
  - platform: google_translate

group: !include groups.yaml
automation: !include automations.yaml
script: !include scripts.yaml
scene: !include scenes.yaml
